---
title: "Appendix"
bibliography: references.bib
link-citations: true
output:
  pdf_document:
    number_sections: false
    includes:
      in_header: "preamble.tex"
---

```{r setup}
#| include: false

library(readr)
library(knitr)
library(flextable)
library(officer)

knitr::opts_chunk$set(echo = FALSE)
```

This appendix includes detailed descriptions of all model equations and input assumptions.

### Annual automation budget on a **per mile** basis

\begin{multline}
annual\_automation\_budget = (fare\_per\_mile \times utilization\_rate)\\ - (financing + licensing + insurance +  maintenance + fuel + labor) 
\end{multline}

\newpage

### Net Present Value of Automation Budget

| Variable Name     | Value  | Source                  |
|-------------------|--------|-------------------------|
| av_tech_lifespan  | 5      | Assumption              |
| vehicle_lifespan  | 5      | @nunes2020; @nytlc2014  |
| discount rate (i) | 5%     | @compostella2020        |
| mileage_annual    | 65,000 | @uitp2020; @tlc2014     |
| fare_per_mile     | \$5.00 | @cityofchicago; @nytlc  |
| utilization_rate  | 50%    | @cramer2016; @nunes2020 |

**Year 0:** Initial investment = `net_present_automation_budget`

**Year 1 to Vehicle Lifespan:** Annual automation budget

**Year \> Vehicle Lifespan:** Annual automation budget without vehicle financing

\begin{equation}
net\_present\_automation\_budget = \sum_{k=1}^{n} \frac{annual\_automation\_budget \times mileage\_annual}{(1+i)^{k}}
\end{equation}

\newpage

### Financing

| Variable Name              | Value    | Source                            |
|----------------------------|----------|-----------------------------------|
| vehicle_price              | \$28,000 | @compostella2020                  |
| annual_interest_rate       | 7%       | @nunes2020                        |
| vehicle_financing_lifespan | 3 years  | @nunes2020                        |
| vehicle_lifespan           | 5        | @nunes2020                        |
| payment_periods_per_year   | 12       | Assuming monthly payments         |
| mileage_annual             | 65,000   | @nytlc; @uitp2020; @cityofchicago |

Equations:

\begin{equation}
monthly\_loan\_payment = \frac{vehicle\_price}{([(1+i)^n - 1] \div [i(1+i)^n]}
\end{equation}

\begin{equation}
n = payment\_periods\_per\_year \times vehicle\_financing\_lifespan
\end{equation}

\begin{equation}
i = \frac{annual\_interest\_rate}{months\_per\_year}
\end{equation}

\begin{equation}
total\_loan\_payment = monthly\_loan\_payment \times months\_per\_year \times vehicle\_financing\_duration
\end{equation}

\begin{equation}
financing = \frac{total\_loan\_payment}{miles\_per\_year \times vehicle\_lifespan}
\end{equation}

\newpage

### Licensing

It is currently unclear whether robotaxis will be regulated under taxi or Transportation Network Company guidelines, which have differing licensing costs. See below for the calculation of taxi and TNC licensing fees.

**Taxi Licensing - Chicago**

The following costs are on a **per vehicle** basis

| Variable Name                            | Value             | Source    |
|------------------------------------------|-------------------|-----------|
| taxi_licensing_taxi_medallion_license    | \$500 per 2 years | @bacp2020 |
| taxi_licensing_ground_transportation_tax | \$98/month        | @bacp2020 |
| taxi_licensing_accessibility_fund        | \$22/month        | @bacp2020 |
| taxi_licensing_advertising_fee           | \$100/year        | @bacp2020 |

Equations:

\begin{multline}
annual\_licensing\_taxi = taxi\_licensing\_taxi\_medallion\_license\\ + (taxi\_licensing\_ground\_transportation\_tax + taxi\_licensing\_accessibility\_fund) \times months\_per\_year\\ + taxi\_licensing\_advertising\_fee 
\end{multline}

\begin{equation}
licensing = \frac{annual\_licensing\_taxi}{miles\_per\_year}
\end{equation}

**TNC Licensing - Chicago**

The City of Chicago identified 148,351 unique TNC drivers in a recent study @bacp2023a. Only a fraction of these drivers, however, were categorized as full-time drivers. We assume robotaxis would operate on a full-time basis and thus use the mean number of full-time TNC drivers (1,313) as the fleet size for TNC licensing calculations.

| Variable Name                    | Value                     | Source         |
|------------------------------|------------------------|-----------------|
| tnc_licensing_admin_fee_per_year | \$10,000/year per company | @bacp2020      |
| tnc_licensing_admin_fee_per_trip | \$0.02/trip               | @bacp2020      |
| tnc_licensing_ground_transport   | \$1/trip                  | @bacp2020      |
| tnc_licensing_access_fund        | \$0.10/trip               | @bacp2020      |
| tnc_licensing_advertising_fee    | \$100/year per vehicle    | @bacp2020      |
| fleet_size                       | 1,313 vehicles            | @bacp2023a     |
| miles_per_trip                   | 3.09 miles                | @cityofchicago |

\begin{multline}
licensing\_tnc = \frac{tnc\_licensing\_admin\_fee\_tnc\_per\_year}{miles\_per\_year \times fleet\_size} \\ + \frac{tnc\_licensing\_admin\_fee\_tnc\_per\_trip + tnc\_licensing\_ground\_transport\_tnc + access\_fund\_tnc}{miles\_per\_trip} \\ + \frac{tnc\_licensing\_advertising\_fee}{miles\_per\_year} 
\end{multline}

**Taxi Licensing - New York City**

In New York City, taxi licensing occurs through the purchase of a taxi medallion. A down payment of 20% is applied with 25% of the down payment paid upfront and the remainder of the down payment financed over 5 years. The remaining balance is financed over 7 years.

| Variable Name                | Value     | Source                              |
|-------------------------|----------------|-------------------------------|
| taxi_medallion_price         | \$255,000 | @newyorkcitytaxilimousinecommission |
| downpayment_percent          | 20%       | @nunes2020                          |
| downpayment_upfront_percent  | 25%       | @nunes2020                          |
| financing_period_downpayment | 7 years   | @nunes2020                          |
| financing_period_remainder   | 5 years   | @nunes2020                          |
| medallion_interest_rate      | 5.4%      | @nunes2020                          |
| payment_periods_per_year     | 12        | @nunes2020                          |
| medallion_lifespan           | 20        | @nunes2020                          |

Equations:

\begin{equation}
n_d = payment\_periods\_per\_year \times financing\_period\_downpayment
\end{equation}

\begin{equation}
n_r = payment\_periods\_per\_year \times financing\_period\_remainder
\end{equation}

\begin{equation}
i = \frac{medallion\_interest\_rate}{months\_per\_year}
\end{equation}

\begin{equation}
downpayment\_total = downpayment\_percent \times  taxi\_licensing\_taxi\_medallion\_price
\end{equation}

\begin{equation}
downpayment\_upfront = downpayment\_upfront\_percent \times downpayment\_total
\end{equation}

\begin{equation}
downpayment\_remainder = downpayment\_total - downpayment\_upfront
\end{equation}

\begin{equation}
downpayment\_monthly\_loan\_payment = \frac{downpayment\_remainder}{([(1+i)^n_d - 1] \div [i(1+i)^n_d]}
\end{equation}

\begin{equation}loan\_remainder = taxi\_licensing\_taxi\_medallion\_price - downpayment\_total
\end{equation}

\begin{equation}
remainder\_monthly\_loan\_payment = \frac{loan\_remainder}{([(1+i)^n_r - 1] \div [i(1+i)^n_r]}
\end{equation}

\begin{equation}
\begin{aligned}
total\_medallion\_payment = downpayment\_upfront \\ + (downpayment\_monthly\_loan\_payment \times n_d) \\ + (remainder\_monthly\_loan\_payment \times n_r) 
\end{aligned}
\end{equation}

\begin{equation}
licensing = \frac{total\_medallion\_payment}{miles\_per\_year \times medallion\_lifespan}
\end{equation}

\newpage

### Insurance

For the base model, the `av_operations_factor` is 1. The listed `av_operations_factor` is used in the Advanced AV Tech scenario.

| Variable Name                  | Value       | Source                    |
|--------------------------------|-------------|---------------------------|
| vehicle_operations_insurance   | \$682/month | @bodine2023; @taxiins2023 |
| av_operations_factor_insurance | 0.5         | @fagnant2016              |

Equation:

\begin{equation}
insurance = \frac{vehicle\_operations\_insurance \times months\_per\_year}{miles\_per\_year} \times av\_operations\_factor\_insurance
\end{equation}

\newpage

### Maintenance

We assume maintenance costs are \$0.06/mi. For the base model, the `av_operations_maintenance` factor is 1. The listed `av_operations_maintenance` factor is used in the Advanced AV Tech scenario.

| Variable Name                    | Value     | Source                   |
|----------------------------------|-----------|--------------------------|
| vehicle_operations_maintenance   | \$0.06/mi | @parrott2018; @reich2020 |
| av_operations_factor_maintenance | 0.9       | @fagnant2016             |

Equation:

\begin{equation}
maintenance = vehicle\_operations\_maintenance \times av\_operations\_factor\_maintenance
\end{equation}

\newpage

### Fuel

For the base model, the `av_operations_fuel` factor is 1. The listed `av_operations_fuel` factor is used in the Advanced AV Tech scenario.

| Variable Name             | Value               | Source                    |
|--------------------------|--------------------|--------------------------|
| fuel_cost_per_gal         | \$3.829/gallon      | @aaa2023                  |
| fuel_efficiency           | 45 miles per gallon | @epa2021                  |
| av_operations_factor_fuel | 0.8                 | @stephens2016; @bösch2018 |

Equations:

\begin{equation}
annual\_fuel\_cost = \frac{miles\_per\_year}{fuel\_efficiency} \times fuel\_cost\_per\_gal
\end{equation}

\begin{equation}
fuel = \frac{annual\_fuel\_cost}{miles\_per\_year} \times av\_operations\_factor\_fuel
\end{equation}

\newpage

### Labor

Overall equation:

\begin{equation}
labor = cleaning + customersupport + fieldsupport + monitor
\end{equation}

#### Cleaning

We assume the vehicles receive a basic cleaning daily, and a deep cleaning 3 times per week. We assume that one cleaner can perform a basic cleaning for 50 vehicles in one hour, and that one cleaner can perform a deep cleaning for 10 vehicles in 3 hours. In the City of Chicago, minimum wage is \$15.80 per hour.

| Variable Name                      | Value         | Source     |
|------------------------------------|---------------|------------|
| shift_days_per_year_cleaner_basic  | 365 days/year | Assumption |
| shift_days_per_year_cleaner_deep   | 156 days/year | Assumption |
| shift_length_cleaner_basic         | 1 hour        | Assumption |
| shift_length_cleaner_deep          | 3 hours       | Assumption |
| vehicles_per_cluster_cleaner_basic | 12            | Assumption |
| vehicles_per_cluster_cleaner_deep  | 10            | Assumption |
| wage_cleaner                       | \$15.80       | @bacp2023  |

Equations: 

\begin{equation}
\begin{aligned}
cluster\_cost\_cleaner\_basic = shift\_length\_cleaner\_basic \times shift\_days\_per\_year\_cleaner\_basic \\ \times workers\_per\_shift\_cleaner\_basic \times wage\_cleaner 
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
cluster\_cost\_cleaner\_deep = shift\_length\_cleaner\_deep \times shift\_days\_per\_year\_cleaner\_deep \\ \times workers\_per\_shift\_cleaner\_deep \times wage\_cleaner 
\end{aligned}
\end{equation}

\begin{equation}
cost\_per\_cluster\_cleaner = cluster\_cost\_cleaner\_basic + cluster\_cost\_cleaner\_deep 
\end{equation}

\begin{equation}
cleaning = \frac{cost\_per\_cluster\_cleaner}{vehicles\_per\_cluster \times miles\_per\_year}
\end{equation}

#### Field Support

| Variable Name                    | Value                   | Source      |
|----------------------------------|-------------------------|-------------|
| shift_days_per_year_fieldsupport | 365 days/year           | @kaplan2023 |
| shift_length_fieldsupport        | 8 hours                 | @kaplan2023 |
| wage_fieldsupport                | \$23/hr                 | @adecco2023 |
| workers_per_shift_fieldsupport   | 1 per shift per cluster | Assumption  |
| vehicles_per_cluster             | 20                      | Assumption  |
| overhead_rate                    | 1.59                    | @nunes2020  |

Equations:

\begin{equation}
\begin{aligned}
fieldsupport\_per\_day = workers\_per\_shift\_fieldsupport \times \frac{hours\_per\_day}{shift\_length\_fieldsupport} 
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned} 
cluster\_cost\_fieldsupport = (shift\_days\_per\_year\_fieldsupport \times shift\_length\_fieldsupport \\ \times wage\_fieldsupport \times overhead\_rate \times 1) \\ +
    (shift\_days\_per\_year\_fieldsupport \times shift\_length\_fieldsupport \times wage\_fieldsupport \\ \times (fieldsupport\_per\_day - 1)) 
\end{aligned}
\end{equation}

\begin{equation}
miles\_per\_cluster = vehicle\_annual\_miles \times vehicles\_per\_cluster
\end{equation}

\begin{equation}
fieldsupport = \frac{cluster\_cost\_fieldsupport}{miles\_per\_cluster}
\end{equation}

#### Remote Monitor

| Variable Name               | Value                   | Source         |
|-----------------------------|-------------------------|----------------|
| shift_days_per_year_monitor | 365 days/year           | @kaplan2023    |
| shift_length_monitor        | 8 hours                 | @pawlowski2011 |
| wage_monitor                | \$21/hr                 | @iconma2023    |
| workers_per_shift_monitor   | 1 per shift per cluster | Assumption     |
| vehicles_per_cluster        | 10                      | Assumption     |
| overhead_rate               | 1.59                    | @nunes2020     |

Equations:

\begin{equation}
\begin{aligned} 
monitor\_per\_day = workers\_per\_shift\_monitor \times \frac{hours\_per\_day}{shift\_length\_monitor} 
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned} 
cluster\_cost\_monitor = (shift\_days\_per\_year\_monitor \times shift\_length\_monitor \\ \times wage\_monitor \times overhead\_rate \times 1) \\ +
    (shift\_days\_per\_year\_monitor \times shift\_length\_monitor \times wage\_monitor \\ \times (monitor\_per\_day - 1)) 
\end{aligned}
\end{equation}

\begin{equation}
miles\_per\_cluster = vehicle\_annual\_miles \times vehicles\_per\_cluster
\end{equation}

\begin{equation}
monitor = \frac{cluster\_cost\_monitor}{miles\_per\_cluster}
\end{equation}

#### Customer Support

| Variable Name                       | Value                   | Source                   |
|------------------------------|---------------------|----------------------|
| shift_days_per_year_customersupport | 365 days/year           | @kaplan2023              |
| shift_length_customersupport        | 8 hours                 | @pawlowski2011           |
| wage_customersupport                | \$21/hr                 | @indeed2023; @iconma2023 |
| workers_per_shift_customersupport   | 1 per shift per cluster | Assumption               |
| vehicles_per_cluster                | 50                      | Assumption               |
| overhead_rate                       | 1.59                    | @nunes2020               |

Equations:

\begin{equation}
customersupport\_per\_day = workers\_per\_shift\_customersupport \times \frac{hours\_per\_day}{shift\_length\_customersupport} 
\end{equation}

\begin{equation}
\begin{aligned} cluster\_cost\_customersupport = (shift\_days\_per\_year\_customersupport \times shift\_length\_customersupport \\ \times wage\_customersupport * overhead\_rate * 1) \\ + (shift\_days\_per\_year\_customersupport \times shift\_length\_customersupport \\ \times wage\_customersupport \times (customersupport\_per\_day - 1)) 
\end{aligned} 
\end{equation}

\begin{equation}
miles\_per\_cluster = vehicle\_annual\_miles \times vehicles\_per\_cluster 
\end{equation}

\begin{equation}
customersupport = \frac{cluster\_cost\_customersupport}{miles\_per\_cluster}
\end{equation}

# Description of Monte Carlo simulation inputs

Please see the `inputs_monte_carlo.xlsx` file.

\newpage

## References
